app:
  name: test
  language: en-US
  supportLanguages:
  - zh-CN
  - en-US
  env: DEV
  host: 127.0.0.1
  port: 8080

database:
  url: jdbc:hsqldb:mem:db;sql.syntax_mys=true
  createTableEnabled: true

email:
  url: http://localhost

web:
  cacheEnabled: false
  roots:
  - C:\Users\chi\Workspace\jweb-cms-project\jweb-main\src\main\web
  - C:\Users\chi\Workspace\jweb-cms-project\jweb-page\page-web\src\main\web
  - C:\Users\chi\Workspace\jweb-cms-project\jweb-page\page-admin\src\main\dist\web
  - C:\Users\chi\Workspace\jweb-cms-project\jweb-user\user-admin\src\main\dist\web
  - C:\Users\chi\Workspace\jweb-cms-project\jweb-file\file-admin\src\main\dist\web

user:
  defaultAdminUser:
    username: admin
    password: admin

user-web:
  google:
    clientId: 219296248573-i60mnhnk75lshj2lihsc5047ik3v6qj6.apps.googleusercontent.com
    clientSecret: IBtWhvY1ZkwB9guRsdT4OXPl
    callback: http://localhost:8080/user/oauth/callback
  facebook:
    clientId: 244833756222750
    clientSecret: 40f70636aec726fa91443ad4768f322a
    callback: http://localhost:8080/user/oauth/callback