app:
  name: test
  language: zh-CN
  supportLanguages:
  - zh-CN
  - en-US
  env: DEV
  host: 127.0.0.1
  port: 8080

page-web:
  theme: cerulean

database:
  url: jdbc:mysql://localhost:3306/main?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: root
  createTableEnabled: true

email:
  url: http://localhost

web:
  cacheEnabled: false
  roots:
  - ../../../../jweb-admin/src/main/dist/web
  - ../../../../jweb-email/email-admin/src/main/dist/web
  - ../../../../jweb-user/user-admin/src/main/dist/web
  - ../../../../jweb-user/user-web/src/main/web
  - ../../../../jweb-user/captcha-web-simple/src/main/web
  - ../../../../jweb-user/pincode-web/src/main/web
  - ../../../../jweb-file/file-admin/src/main/dist/web
  - ../../../../jweb-page/page-web/src/main/web
  - ../../../../jweb-page/page-admin/src/main/dist/web
  - ../../../../jweb-web/src/main/web
  - ../../../../jweb-comment/comment-admin/src/main/dist/web
  - ../../../../jweb-comment/comment-web/src/main/web

user:
  defaultAdminUser:
    username: admin
    password: admin